export const PATH = {
  ROOT_PAGE: '/',
  LOGIN_PAGE: '/login',
  SIGNUP_PAGE: '/signup',
  OVERVIEW_PAGE: '/overview',
  BUILD_FORM_PAGE: '/build',
  EDIT_FORM_PAGE: '/build/:id',
  MY_ACCOUNT_PAGE: '/my-account',
  STATISTIC_PAGE: '/statistic/:formId',
  PUBLIC_PAGE: '/form/:id',
  RESPONSE_PAGE: '/responses/:formId',
  TEMPLATES_PAGE: '/templates',
  CREATE_TEMPLATE: '/template',
  EDIT_TEMPLATE: '/template/:id',
};
